rails_app/config/routes.rb
Auth::Application.routes.draw do

  resources :reports do
    collection do
      get 'check_homework' => 'reports#check'
    end
  end

  controller :logger do
    get 'logger' => :index
    post 'logger' =>  :load
  end

  controller :statistic do
    get 'statistic' => :index
    get 'statistic/language' => :language
    
  end

  controller :support do
    get 'support/database_restore' => :select
    post 'support/database_restore' => :restore
    get 'support/database_back_up' => :back_up
    get 'support/destroy' => :destroy   
  end

      
  # devise_for :users
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy' 
  end

  mount Resque::Server, :at => "/resque"
  
  root :to => "reports#index"
end

rails_app/app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta{:charset => 'utf-8', 'http-equiv' => 'X-UA-Compatible', :content => 'IE=Edge,chrome=1', :name => 'viewport', :content => 'width=device-width, initial-scale=1.0'}
    %title= content_for?(:title) ? yield(:title) : 'HWC'
    = csrf_meta_tags
    
    = stylesheet_link_tag 'application', :media => 'all'

  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          = link_to 'Home Work Checker', '/', :class => :brand
          .container.nav-collapse
            %ul.nav
              - if user_signed_in?
                %li
                  .btn-group
                    %a{ :class => 'btn dropdown-toggle', 'data-toggle' => 'dropdown', :href => '#'}
                      Actions
                      %span.caret
                    %ul{ :class => 'dropdown-menu'}
                      %li
                        =link_to 'Back up database', support_database_back_up_path
                      %li
                        =link_to 'Clear students & homeworks', support_destroy_path
                      %li{ :class => 'divider'}
                      %li
                        =link_to 'Check homeworks', :controller => :reports, :action => :check
                %li
                  = link_to current_user.email, reports_path
                %li 
                  = link_to 'Sign out', destroy_user_session_path
              - else
                %li
                  = link_to 'Sign up', new_user_registration_path
                %li
                  = link_to 'Sign in', new_user_session_path

    .container-fluid
      .row-fluid
        .span3
          .well.sidebar-nav
            %ul.nav.nav-list
              %li.nav-header Main Menu
              %li= link_to 'Results Overview', reports_path
              %li= link_to "Queue's Page", resque_server_path
              %li= link_to 'General Statistic', statistic_path
              %li= link_to 'Language Statistic', statistic_language_path
              %li= link_to 'Logger', logger_path
              %li= link_to 'Restore Database', support_database_restore_path
        .span9
          = bootstrap_flash
          = yield
    
    %div{ :class => 'navbar navbar-fixed-bottom text-center' }
      %p &copy; SoftServe 2013


    /when everything is loaded
    = javascript_include_tag 'application'

  