rails_app/config/routes.rb
Auth::Application.routes.draw do

  resources :reports do
    collection do
      get 'check_homework' => 'reports#check'
    end
  end

  controller :logger do
    get 'logger' => :index
    post 'logger' =>  :load
  end

  controller :statistic do
    get 'statistic' => :index
    get 'statistic/language' => :language
    
  end

  controller :support do
    get 'support/database_restore' => :select
    post 'support/database_restore' => :restore
    get 'support/database_back_up' => :back_up
    get 'support/destroy' => :destroy   
  end

      
  # devise_for :users
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy' 
  end

  mount Resque::Server, :at => "/resque"
  
  root :to => "reports#index"
end

rails_app/app/models/report.rb
class Report < ActiveRecord::Base
  ARCHIVE_PATH, RESULT_PATH = YAML.load_file(Rails.root + 'config/path.yml').values
  LOG_PATH = Rails.root + 'log'
  ARCHIVE_PASSED = ' have successfully processed'
  ARCHIVE_FAILED = ' have failed. Something went wrong'
  MONTHS_LIST = {
    '01' => 'January',
    '02' => 'February',
    '03' => 'March',
    '04' => 'April',
    '05' => 'May',
    '06' => 'June',
    '07' => 'Jule',
    '08' => 'August',
    '09' => 'September',
    '10' => 'October',
    '11' => 'November',
    '12' => 'December'
  } 

  attr_accessible :homework_id, :quality, :ratio, :student_id, :time
  belongs_to :student
  belongs_to :homework

  validates_presence_of :quality, :ratio, :time

  validates_numericality_of :quality, :ratio, {
    greater_than_or_equal_to: 0.00,
    less_than_or_equal_to: 100.00
  }
  validates_numericality_of :time, greater_than: 0.00


  def self.homework_check
    begin
      HomeWorkChecker::FileScan.new(ARCHIVE_PATH, RESULT_PATH).each do |name, type|
        Resque.enqueue(ArchiveChecker, ARCHIVE_PATH, RESULT_PATH, name, type)
      end
    rescue HomeWorkChecker::DirectoryExistError, HomeWorkChecker::DirectoryFormatError, RuntimeError => error
      logger = OwnLogger::HomeWorkChecker.new(LOG_PATH)
      logger.add_line(error.message)
    end
  end

  def self.archive_passed(archive_name)
    "Archive '#{archive_name}'#{ARCHIVE_PASSED}"
  end

  def self.archive_failed(archive_name)
    "Archive '#{archive_name}'#{ARCHIVE_FAILED}"
  end

  def self.add_record(fn)
    xml_content = xml_file_to_hash(fn)
    s = Student.where(
      name: xml_content[:student]
    ).first_or_create
    h = Homework.where(
      title: xml_content[:homework],
      language: xml_content[:language]
    ).first_or_create

    s.reports.create(
      homework_id: h.id,
      ratio: xml_content[:ratio],
      quality: xml_content[:quality],
      time: xml_content[:time]
    ).valid?
  end

  def self.find_files_to_download
    logger = OwnLogger::HomeWorkChecker.new(LOG_PATH)
    logger.find_files_to_download
  end

  def self.compress_log_files
    year_prev = Time.now.to_s[0..3].to_i
    logger = OwnLogger::HomeWorkChecker.new(LOG_PATH)
    logger.compress_files(year_prev)
  end

  private
  def self.xml_file_to_hash(fn)
    Nokogiri::XML(File.open(fn, 'r')).xpath('//root').map do |f|
      {
        student: f.xpath('student').inner_text,
        homework: f.xpath('homework').inner_text,
        language: f.xpath('language').inner_text,
        ratio: f.xpath('ratio').inner_text.to_f,
        quality: f.xpath('quality').inner_text.to_f,
        time: f.xpath('time').inner_text.to_f
      }
    end.first
  end
end

rails_app/app/controllers/reports_controller.rb
class ReportsController < ApplicationController
   before_filter :authenticate_user!

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
    # binding.pry
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report = Report.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/new
  # GET /reports/new.json
  def new
    @report = Report.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/1/edit
  def edit
    @report = Report.find(params[:id])
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(params[:report])

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render json: @report, status: :created, location: @report }
      else
        format.html { render action: "new" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.json
  def update
    @report = Report.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end

  def check
    count = Report.homework_check.length
    flash[:info] = ( count > 0 ? "#{count} archive(-s)" : 'No one archive' ) + ' was added to queue'
    redirect_to root_path
  end
end

rails_app/app/views/reports/_form.html.haml
= form_for @report, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :student_id, :class => 'control-label'
    .controls
      = f.number_field :student_id, :class => 'number_field'
  .control-group
    = f.label :homework_id, :class => 'control-label'
    .controls
      = f.number_field :homework_id, :class => 'number_field'
  .control-group
    = f.label :ratio, :class => 'control-label'
    .controls
      = f.text_field :ratio, :class => 'text_field'
  .control-group
    = f.label :quality, :class => 'control-label'
    .controls
      = f.text_field :quality, :class => 'text_field'
  .control-group
    = f.label :time, :class => 'control-label'
    .controls
      = f.text_field :time, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), reports_path, :class => 'btn'

rails_app/app/views/reports/edit.html.haml
- model_class = Report
.page-header
  %h3=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

rails_app/app/views/reports/index.html.haml
%h3 Results Overview

%table{:class => 'data-table display'}
  %thead
    %tr
      %th Student
      %th Homework
      %th Language
      %th Ratio
      %th Quality
      %th Time
  
  %tbody
    - @reports.each do |report|
      %tr
        %td= report.student.try(:name)
        %td= report.homework.try(:title)
        %td= report.homework.try(:language)
        %td= report.ratio
        %td= report.quality
        %td= report.time
        

rails_app/app/views/reports/log.html.haml
%h2 System Log

= form_tag nil, :class => 'form-horizontal' do

  - if flash[:wrong] 
    %div{ :class => "alert alert-error" }
      = flash[:wrong] 

  .control-group
    = label_tag :year, nil, :class => 'control-label'
    .controls
      = select_tag :year, options_for_select(@years), :prompt => 'Please select', :class => 'select', :id => 'select-year'

  .control-group
    = label_tag :month, nil, :class => 'control-label'
    .controls
      = select_tag :month, options_for_select(@months), :prompt => 'Please select', :class => 'select', :id => 'select-month'

  .form-actions
    = submit_tag 'Download file', :class => 'btn btn-primary'
    = link_to 'Cancel', reports_path, :class => 'btn'

rails_app/app/views/reports/new.html.haml
- model_class = Report
.page-header
  %h3=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

rails_app/app/views/reports/show.html.haml
- model_class = Report
.page-header
  %h3=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:student_id) + ':'
  %br
  = @report.student_id
%p
  %strong= model_class.human_attribute_name(:homework_id) + ':'
  %br
  = @report.homework_id
%p
  %strong= model_class.human_attribute_name(:ratio) + ':'
  %br
  = @report.ratio
%p
  %strong= model_class.human_attribute_name(:quality) + ':'
  %br
  = @report.quality
%p
  %strong= model_class.human_attribute_name(:time) + ':'
  %br
  = @report.time

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), reports_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_report_path(@report), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), report_path(@report), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'